version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_db
    volumes:
      - ./ddl-init.sql:/docker-entrypoint-initdb.d/init.sql  # создаём таблицы БД
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: always